name: Create Issue with Movie Options

on:
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: "{Movie here} or {Movie here}?"
          content-filepath: issue_content.md
